apiVersion: openinfradev.github.com/v1
kind: HelmValuesTransformer
metadata:
  name: site

global:
  clusterName: cluster.local
charts:
- name: cluster-api-aws
  override:
    sshKeyName: tks-seoul
    cluster.name: $(clusterName)
    cluster.region: ap-northeast-2
    cluster.bastion.enabled: false
    machinePool:
    - name: taco
      machineType: t3.2xlarge
      replicas: 3
      minSize: 1
      maxSize: 16
      rootVolume:
        size: 200
        type: gp2
      labels:
        taco-lma: enabled
        servicemesh: enabled
        taco-ingress-gateway: enabled
    machineDeployment:
    - name: normal
      numberOfAZ: 3
      minSizePerAZ: 1
      maxSizePerAZ: 5
      selector:
        matchLabels:
      machineType: t3.large
      rootVolume:
        size: 50
        type: gp2

- name: kubernetes-addons
  override:
    cni.calico.enabled: true

- name: aws-ebs-csi-driver
  override:

- name: ingress-nginx
  override:

- name: cluster-autoscaler
  override:
    discoveryNamespace: $(clusterName)
    discoveryClusterName: $(clusterName)
